services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/data
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data: